### ISSUE TITLE
help!!

### ISSUE THREAD

**Issue by KENPOKASMMA1982** [g1g0byte/spotify-downloader#1]
my friend I uninstall python for some reason and now I cant download!!!please help me!which version of python I must install and tell me which pip I need and the steps to run your project!!!I will preciate it man!

**Comment by g1g0byte** [comment]
Hi!

I'm using the latest version of Python 3.9:
https://www.python.org/downloads/release/python-3912/

Not sure how other versions of Python are supported, I'll need to check that out.

I've been using pip 21.2.4 but any version should be fine.

To get the spotDL library to work you'll need to add python to PATH environment variable.
You also need to install FFMPEG and add it to PATH:
https://windowsloop.com/install-ffmpeg-windows-10/

After that you'll just need to install the dependencies using the "pyproject.toml" file.

Hopefully this helps you get it working, I'm still a beginner to this stuff. I'll make sure to get instructions up on the readme.
Let me know if you still need help or have any suggestions, thanks :)

**Comment by KENPOKASMMA1982** [comment]
MY FRIENDDDDDDDDD THANKSSSSSSSSSSS SO MUCH!BUT PLEASE TELL ME DO YOU HAVE FACEBOOK?IF YES THIS IS MINE https://www.facebook.com/panos.papadopulos/

**Comment by g1g0byte** [comment]
Love your enthusiasm 😄 I'm afraid I don't use Facebook though. 
Did you manage to get the project working?

**Comment by KENPOKASMMA1982** [comment]
MY FRIEND DO YOU KNOW PLEASE THE ANYDESK?IS PROGRAMM TO ENTER TO MY PC TO HELP ME!!!PLEASEEEEEEEEEEEEE

**Comment by KENPOKASMMA1982** [comment]
https://anydesk.com/en/downloads/windows

**Comment by KENPOKASMMA1982** [comment]
PLEASE CAN YOU DOWNLOAD IT AND ENTER FOR FEW MINUTES TO HELP ME?I WILL PRECIATE ITTTTTTTTT SO MUCH!!!THIS IS MY CODE 779270404

**Comment by KENPOKASMMA1982** [comment]
what you think man?can you enter?or can you write me when install python all the correct commands to run python on cmd and pip also?

**Comment by g1g0byte** [comment]
What I'll do is when I make my first release soon, I will make an executable file. So you will just need to download and run it to get the project running.
